apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
stringData:
  DATABASE_URL: mysql+pymysql://your-username:your-Password@your-rds-endpoint:3306/db-name
  REDIS_URL: redis://redis-endpoint:6379/0

  JWT_SECRET_KEY: your-secret-key
  JWT_ALGORITHM: HS256
  JWT_EXPIRATION_HOURS: "24"

  GOOGLE_CLIENT_ID: your-google-client-id
  GOOGLE_CLIENT_SECRET: your-google-secret
  GOOGLE_REDIRECT_URI: your-redirect-uri

  SMTP_HOST: smtp.gmail.com
  SMTP_PORT: "587"
  SMTP_USER: your-email
  SMTP_PASSWORD: your-password
  EMAIL_FROM: your-email

  FRONTEND_URL: https://your-domain-name
